### ISSUE TITLE
Skills Reminders for New/Edit Job and Candidate

### ISSUE THREAD

**Issue by LaustinSpayce** [weizheng1910/linkdr#73]
When editing a job or editing a candidate. Or creating a new job or creating a new candidate:

There should be a reminder (and hopefully validation) that a job can have maximum 5 skills, and a candidate can have maximum 10 skills.

We can have these hard coded in for now. They are hard coded in the models.

If anyone can figure out how to hard code this into pSQL that'd be even better. 🥳

**Comment by rachellesg** [comment]
hard coded with javascript to only allow max 5 skills (jobs) and 10 skills (candidates)
