### ISSUE TITLE
"Choosiness" for skills matches

### ISSUE THREAD

**Issue by LaustinSpayce** [weizheng1910/linkdr#81]
A company may want a job to be applied to by candidates who do not have all the required skills. They may have 5 skills listed, but candidates applying may only have 3 or 4 of those skills.

We could implement some way for candidates missing 1 or 2 skills could still be put forward, if the company posting the job allows it. (Have a setting when posting or editing a job).

**Comment by rachellesg** [comment]
Agreed on this, could do a 80% relevant rate and allow candidates to express interest

**Comment by benjacoblee** [comment]
(@candidate.skills & @job.skills).length / @job.skills.length
