### ISSUE TITLE
Candidate details failed to save

### ISSUE THREAD

**Issue by tomblakemore** [weizheng1910/linkdr#99]
Steps to error - 

* Signed up as new candidate
* Filled in edit profile screen with -
  * Given name: Tom
  * Family name: Blakemore
  * Bio: Lorem ipsum dolor sit amet...
  * Years of experience: 12
  * Expected salary: 100000
  * Skills: Javascript, HTML, CSS, Node.js, Express.js, Git, PHP
  * Resume: (a JPG file)

![WhatsApp Image 2020-02-21 at 10 20 08](https://user-images.githubusercontent.com/213065/75027122-f1b12480-5495-11ea-86d7-1b1c67b1c559.jpeg)

* Hit "Update Candidate"
* Received error page

![WhatsApp Image 2020-02-21 at 10 19 09](https://user-images.githubusercontent.com/213065/75026970-badb0e80-5495-11ea-9959-5bc4c2d84bb3.jpeg)

* Hit back in the browser
* Change Resume to a PDF file
* Hit "Update Candidate"
* Dashboard page appears but no details entered on previous screen on show (except a thumbnail which looks like it's loaded from Gravatar based on my email)

![WhatsApp Image 2020-02-21 at 10 22 22](https://user-images.githubusercontent.com/213065/75027140-f83f9c00-5495-11ea-901b-94b42f32db95.jpeg)

* Click the pencil button
* Re-enter all details and PDF
* Hit "Update Candidate"
* Dashboard page now shows entered details

![WhatsApp Image 2020-02-21 at 10 23 52](https://user-images.githubusercontent.com/213065/75027148-fc6bb980-5495-11ea-914e-3baa7a82c60b.jpeg)

**Comment by rachellesg** [comment]
Found the problem: The profile does not update if candidate bio is too long, need to change the bio input field from textarea to text field restrict number of characters for text area OR update the bio table to be text.

**Comment by LaustinSpayce** [comment]
Fixed bio length restriction in PR #125.
